kind: ConfigMap
apiVersion: v1
metadata:
  name: acc-ui-configmap
data:
  ACC_ENVIRONMENT: at
  NEW_RELIC_APP_NAME: acc-at
  SERVER_URL: https://www-acc-at.apps.ocp4.innovateuk.ukri.org
  USE_SSO: "false"
