import { mergeSchemas } from "@graphql-tools/schema";
import { writeFileSync } from "fs";
import { printSchema } from "graphql";
import { getAutogeneratedGraphQLSchema, IAutogeneratedGraphQLSchemaProps } from "./getAutogeneratedGraphQLSchema";
import { getTypeGraphQLSchema } from "./typegraphql/schema";

const getGraphQLSchema = async (props: IAutogeneratedGraphQLSchemaProps) => {
  const autogeneratedSchema = await getAutogeneratedGraphQLSchema(props);
  const typeGraphQLSchema = await getTypeGraphQLSchema();

  const schema = mergeSchemas({
    schemas: [autogeneratedSchema, typeGraphQLSchema],
  });

  // Write the GraphQL schema to a file.
  writeFileSync("schema.gql", printSchema(schema), { encoding: "utf-8" });

  return schema;
};

export { getGraphQLSchema };
