import { Logger } from "@shared/developmentLogger";
import express from "express";
import { GraphQLSchema } from "graphql";
import { createHandler } from "graphql-http/lib/use/express";
import { Api } from "./sfdc-graphql-endpoint/src/sfdc/api";
import { Connection } from "./sfdc-graphql-endpoint/src/sfdc/connection";

interface IAutogeneratedGraphQL {
  api?: Api;
  connection?: Connection;
  schema: GraphQLSchema;
}

const getGraphQLRoutes = async ({ schema, connection, api }: IAutogeneratedGraphQL) => {
  const router = express.Router();

  router.use(
    "/graphql",
    createHandler({
      schema,
      context: {
        api,
        connection,
        logger: new Logger("GraphQL"),
      },
    }),
  );

  return router;
};

export { getGraphQLRoutes };
