export type Heading =
  | "Add a partner"
  | "Add types"
  | "Approve a new subcontractor"
  | "Associate Employment"
  | "Associate start date"
  | "Capital usage"
  | "Change a partner's name"
  | "Change Loans Duration"
  | "Change project duration"
  | "Change project scope"
  | "Change remaining grant"
  | "Claim"
  | "Claim documents"
  | "Claim summary"
  | "Claims"
  | "Costs for this period"
  | "Costs summary"
  | "Costs to be claimed"
  | "Dashboard"
  | "Delete draft request"
  | "Directly incurred - Staff"
  | "Drawdown"
  | "Drawdowns"
  | "Exceptions - Equipment"
  | "Exceptions - Equipment documents"
  | "Exceptions - Staff"
  | "Exceptions - Staff documents"
  | "Finance summary"
  | "Forecast"
  | "Forecasts"
  | "Labour"
  | "Loan Drawdown Change"
  | "Loans costs for Industrial participants"
  | "Materials"
  | "Monitoring report"
  | "Monitoring reports"
  | "Other costs"
  | "Other costs 2"
  | "Other costs 3"
  | "Other costs 4"
  | "Other costs 5"
  | "Overheads"
  | "Partner information"
  | "Project change request submitted"
  | "Project change requests"
  | "Project costs"
  | "Project details"
  | "Project documents"
  | "Project overview"
  | "Project setup"
  | "Provide reasons to Innovate UK"
  | "Provide your bank details"
  | "Provide your project location postcode"
  | "Put project on hold"
  | "Reallocate costs"
  | "Reallocate project costs"
  | "Reasons for Innovate UK"
  | "Remove a partner"
  | "Request"
  | "Spend Profile"
  | "Start a new request"
  | "Subcontracting"
  | "Supporting evidence"
  | "Travel and subsistence"
  | "Update forecast"
  | "Uplift";
