export const errors = [
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 0, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "number",
    received: "null",
    path: ["financialVirements", "financialVirementsForCosts", 0, "originalCostsClaimedToDate"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 1, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 2, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 3, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "number",
    received: "null",
    path: ["financialVirements", "financialVirementsForCosts", 3, "originalCostsClaimedToDate"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 4, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "number",
    received: "null",
    path: ["financialVirements", "financialVirementsForCosts", 4, "originalCostsClaimedToDate"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 5, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "number",
    received: "null",
    path: ["financialVirements", "financialVirementsForCosts", 5, "originalCostsClaimedToDate"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 6, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "number",
    received: "null",
    path: ["financialVirements", "financialVirementsForCosts", 6, "originalCostsClaimedToDate"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 7, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "number",
    received: "null",
    path: ["financialVirements", "financialVirementsForCosts", 7, "originalCostsClaimedToDate"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 8, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "number",
    received: "null",
    path: ["financialVirements", "financialVirementsForCosts", 8, "originalCostsClaimedToDate"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 9, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "number",
    received: "null",
    path: ["financialVirements", "financialVirementsForCosts", 9, "originalCostsClaimedToDate"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 10, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "number",
    received: "null",
    path: ["financialVirements", "financialVirementsForCosts", 10, "originalCostsClaimedToDate"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 11, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "number",
    received: "null",
    path: ["financialVirements", "financialVirementsForCosts", 11, "originalCostsClaimedToDate"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 12, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "number",
    received: "null",
    path: ["financialVirements", "financialVirementsForCosts", 12, "originalCostsClaimedToDate"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 13, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "number",
    received: "null",
    path: ["financialVirements", "financialVirementsForCosts", 13, "originalCostsClaimedToDate"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 14, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "number",
    received: "null",
    path: ["financialVirements", "financialVirementsForCosts", 14, "originalCostsClaimedToDate"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 15, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "number",
    received: "null",
    path: ["financialVirements", "financialVirementsForCosts", 15, "originalCostsClaimedToDate"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 16, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "number",
    received: "null",
    path: ["financialVirements", "financialVirementsForCosts", 16, "originalCostsClaimedToDate"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 17, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "number",
    received: "null",
    path: ["financialVirements", "financialVirementsForCosts", 17, "originalCostsClaimedToDate"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 18, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "number",
    received: "null",
    path: ["financialVirements", "financialVirementsForCosts", 18, "originalCostsClaimedToDate"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 19, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "number",
    received: "null",
    path: ["financialVirements", "financialVirementsForCosts", 19, "originalCostsClaimedToDate"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 20, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "number",
    received: "null",
    path: ["financialVirements", "financialVirementsForCosts", 20, "originalCostsClaimedToDate"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 21, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "number",
    received: "null",
    path: ["financialVirements", "financialVirementsForCosts", 21, "originalCostsClaimedToDate"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 22, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "number",
    received: "null",
    path: ["financialVirements", "financialVirementsForCosts", 22, "originalCostsClaimedToDate"],
    message: "forms.errors.invalid_type",
  },
];
ZodError: [
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 0, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "number",
    received: "null",
    path: ["financialVirements", "financialVirementsForCosts", 0, "originalCostsClaimedToDate"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 1, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 2, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 3, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "number",
    received: "null",
    path: ["financialVirements", "financialVirementsForCosts", 3, "originalCostsClaimedToDate"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 4, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "number",
    received: "null",
    path: ["financialVirements", "financialVirementsForCosts", 4, "originalCostsClaimedToDate"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 5, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "number",
    received: "null",
    path: ["financialVirements", "financialVirementsForCosts", 5, "originalCostsClaimedToDate"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 6, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "number",
    received: "null",
    path: ["financialVirements", "financialVirementsForCosts", 6, "originalCostsClaimedToDate"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 7, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "number",
    received: "null",
    path: ["financialVirements", "financialVirementsForCosts", 7, "originalCostsClaimedToDate"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 8, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "number",
    received: "null",
    path: ["financialVirements", "financialVirementsForCosts", 8, "originalCostsClaimedToDate"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 9, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "number",
    received: "null",
    path: ["financialVirements", "financialVirementsForCosts", 9, "originalCostsClaimedToDate"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 10, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "number",
    received: "null",
    path: ["financialVirements", "financialVirementsForCosts", 10, "originalCostsClaimedToDate"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 11, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "number",
    received: "null",
    path: ["financialVirements", "financialVirementsForCosts", 11, "originalCostsClaimedToDate"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 12, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "number",
    received: "null",
    path: ["financialVirements", "financialVirementsForCosts", 12, "originalCostsClaimedToDate"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 13, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "number",
    received: "null",
    path: ["financialVirements", "financialVirementsForCosts", 13, "originalCostsClaimedToDate"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 14, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "number",
    received: "null",
    path: ["financialVirements", "financialVirementsForCosts", 14, "originalCostsClaimedToDate"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 15, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "number",
    received: "null",
    path: ["financialVirements", "financialVirementsForCosts", 15, "originalCostsClaimedToDate"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 16, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "number",
    received: "null",
    path: ["financialVirements", "financialVirementsForCosts", 16, "originalCostsClaimedToDate"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 17, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "number",
    received: "null",
    path: ["financialVirements", "financialVirementsForCosts", 17, "originalCostsClaimedToDate"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 18, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "number",
    received: "null",
    path: ["financialVirements", "financialVirementsForCosts", 18, "originalCostsClaimedToDate"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 19, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "number",
    received: "null",
    path: ["financialVirements", "financialVirementsForCosts", 19, "originalCostsClaimedToDate"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 20, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "number",
    received: "null",
    path: ["financialVirements", "financialVirementsForCosts", 20, "originalCostsClaimedToDate"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 21, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "number",
    received: "null",
    path: ["financialVirements", "financialVirementsForCosts", 21, "originalCostsClaimedToDate"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "string",
    received: "undefined",
    path: ["financialVirements", "financialVirementsForCosts", 22, "costCategoryName"],
    message: "forms.errors.invalid_type",
  },
  {
    code: "invalid_type",
    expected: "number",
    received: "null",
    path: ["financialVirements", "financialVirementsForCosts", 22, "originalCostsClaimedToDate"],
    message: "forms.errors.invalid_type",
  },
];
