apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: innovation-funding-service

build:
  local:
    useDockerCLI: false
    useBuildkit: false
    tryImportMissing: false
    push: true
  tagPolicy:
    envTemplate:
      template: "{{.TAG_ID}}"
  artifacts:
    - image: acc-monorepo-base
      context: .
      docker:
        dockerfile: Dockerfile
        buildArgs:
          ACC_BUILD_TAG: "{{.TAG_ID}}"
          ACC_BUILD_EPOCH: '{{cmd "date" "+%s"}}'
    - image: acc-ui
      context: .
      requires:
        - image: acc-monorepo-base
          alias: ACC_MONOREPO_BASE
      docker:
        dockerfile: packages/app/Dockerfile
    - image: acc-playwright
      context: .
      requires:
        - image: acc-monorepo-base
          alias: ACC_MONOREPO_BASE
      docker:
        dockerfile: packages/playwright-test/Dockerfile

deploy:
  statusCheckDeadlineSeconds: 600
  kustomize:
    buildArgs:
      # Enable KSOPS to add plugins/execute
      - "--enable-alpha-plugins=true"
      - "--enable-exec=true"
    paths:
      - kustomize/env/stub/local/dev

portForward:
  - resourceType: Service
    resourceName: acc-ui-service
    namespace: default
    port: 8080
    localPort: 8080
