apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: acc-ui
build:
  artifacts:
    - image: acc-ui
      docker:
        dockerfile: Dockerfile
manifests:
  kustomize:
    buildArgs:
      # Enable KSOPS to add plugins/execute
      - "--enable-alpha-plugins=true"
      - "--enable-exec=true"
    paths:
      - kustomize/env/stub/local/dev

profiles:
  - name: local
    manifests:
      kustomize:
        buildArgs:
          # Enable KSOPS to add plugins/execute
          - "--enable-alpha-plugins=true"
          - "--enable-exec=true"
        paths:
          - kustomize/env/stub/local/dev

  - name: demo
    manifests:
      kustomize:
        buildArgs:
          # Enable KSOPS to add plugins/execute
          - "--enable-alpha-plugins=true"
          - "--enable-exec=true"
        paths:
          - kustomize/env/aws/demo
  - name: dev
    manifests:
      kustomize:
        buildArgs:
          # Enable KSOPS to add plugins/execute
          - "--enable-alpha-plugins=true"
          - "--enable-exec=true"
        paths:
          - kustomize/env/aws/dev
  - name: perf
    manifests:
      kustomize:
        buildArgs:
          # Enable KSOPS to add plugins/execute
          - "--enable-alpha-plugins=true"
          - "--enable-exec=true"
        paths:
          - kustomize/env/aws/perf
  - name: preprod
    manifests:
      kustomize:
        buildArgs:
          # Enable KSOPS to add plugins/execute
          - "--enable-alpha-plugins=true"
          - "--enable-exec=true"
        paths:
          - kustomize/env/aws/preprod
  - name: prod
    manifests:
      kustomize:
        buildArgs:
          # Enable KSOPS to add plugins/execute
          - "--enable-alpha-plugins=true"
          - "--enable-exec=true"
        paths:
          - kustomize/env/aws/prod
  - name: sysint
    manifests:
      kustomize:
        buildArgs:
          # Enable KSOPS to add plugins/execute
          - "--enable-alpha-plugins=true"
          - "--enable-exec=true"
        paths:
          - kustomize/env/aws/sysint
  - name: uat
    manifests:
      kustomize:
        buildArgs:
          # Enable KSOPS to add plugins/execute
          - "--enable-alpha-plugins=true"
          - "--enable-exec=true"
        paths:
          - kustomize/env/aws/uat
  - name: custom
    manifests:
      kustomize:
        buildArgs:
          # Enable KSOPS to add plugins/execute
          - "--enable-alpha-plugins=true"
          - "--enable-exec=true"
        paths:
          - kustomize/env/stub/custom
