apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: innovation-funding-service
profiles:
  - name: local
    build:
      local:
        useDockerCLI: false
        useBuildkit: false
        tryImportMissing: true
        push: false
      tagPolicy:
        gitCommit:
          ignoreChanges: true
      artifacts: []
    deploy:
      kubeContext: local
      kustomize:
        paths:
          - kustomize/config-mgmt/env/local

  - name: at
    build:
      local:
        useDockerCLI: false
        useBuildkit: false
        tryImportMissing: true
        push: false
      tagPolicy:
        gitCommit:
          ignoreChanges: true
      artifacts: []
    deploy:
      kubeContext: at
      kustomize:
        paths:
          - kustomize/config-mgmt/env/aws/at

  - name: custom
    build:
      local:
        useDockerCLI: false
        useBuildkit: false
        tryImportMissing: true
        push: false
      tagPolicy:
        gitCommit:
          ignoreChanges: true
      artifacts: []
    deploy:
      kubeContext: custom
      kustomize:
        paths:
          - kustomize/config-mgmt/env/aws/custom

  - name: sysint
    build:
      local:
        useDockerCLI: false
        useBuildkit: false
        tryImportMissing: true
        push: false
      tagPolicy:
        gitCommit:
          ignoreChanges: true
      artifacts: []
    deploy:
      kubeContext: sysint
      kustomize:
        paths:
          - kustomize/config-mgmt/env/aws/sysint

  - name: perf
    build:
      local:
        useDockerCLI: false
        useBuildkit: false
        tryImportMissing: true
        push: false
      tagPolicy:
        gitCommit:
          ignoreChanges: true
      artifacts: []
    deploy:
      kubeContext: perf
      kustomize:
        paths:
          - kustomize/config-mgmt/env/aws/perf

  - name: uat
    build:
      local:
        useDockerCLI: false
        useBuildkit: false
        tryImportMissing: true
        push: false
      tagPolicy:
        gitCommit:
          ignoreChanges: true
      artifacts: []
    deploy:
      kubeContext: uat
      kustomize:
        paths:
          - kustomize/config-mgmt/env/aws/uat

  - name: demo
    build:
      local:
        useDockerCLI: false
        useBuildkit: false
        tryImportMissing: true
        push: false
      tagPolicy:
        gitCommit:
          ignoreChanges: true
      artifacts: []
    deploy:
      kubeContext: demo
      kustomize:
        paths:
          - kustomize/config-mgmt/env/aws/demo

  - name: dev
    build:
      local:
        useDockerCLI: false
        useBuildkit: false
        tryImportMissing: true
        push: false
      tagPolicy:
        gitCommit:
          ignoreChanges: true
      artifacts: []
    deploy:
      kubeContext: dev
      kustomize:
        paths:
          - kustomize/config-mgmt/env/aws/dev

  - name: capdev
    build:
      local:
        useDockerCLI: false
        useBuildkit: false
        tryImportMissing: true
        push: false
      tagPolicy:
        gitCommit:
          ignoreChanges: true
      artifacts: []
    deploy:
      kubeContext: dev
      kustomize:
        paths:
          - kustomize/config-mgmt/env/aws/capdev

  - name: capconfig
    build:
      local:
        useDockerCLI: false
        useBuildkit: false
        tryImportMissing: true
        push: false
      tagPolicy:
        gitCommit:
          ignoreChanges: true
      artifacts: []
    deploy:
      kubeContext: dev
      kustomize:
        paths:
          - kustomize/config-mgmt/env/aws/capconfig

  - name: captest
    build:
      local:
        useDockerCLI: false
        useBuildkit: false
        tryImportMissing: true
        push: false
      tagPolicy:
        gitCommit:
          ignoreChanges: true
      artifacts: []
    deploy:
      kubeContext: dev
      kustomize:
        paths:
          - kustomize/config-mgmt/env/aws/captest

  - name: preprod
    build:
      local:
        useDockerCLI: false
        useBuildkit: false
        tryImportMissing: true
        push: false
      tagPolicy:
        gitCommit:
          ignoreChanges: true
      artifacts: []
    deploy:
      kubeContext: preprod
      kustomize:
        paths:
          - kustomize/config-mgmt/env/aws/preprod

  - name: prod
    build:
      local:
        useDockerCLI: false
        useBuildkit: false
        tryImportMissing: true
        push: false
      tagPolicy:
        gitCommit:
          ignoreChanges: true
      artifacts: []
    deploy:
      kubeContext: prod
      kustomize:
        paths:
          - kustomize/config-mgmt/env/aws/prod
