apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: innovation-funding-service
profiles:
  - name: buildonly
    build:
      local:
        useDockerCLI: false
        useBuildkit: false
        tryImportMissing: false
        push: true
      tagPolicy:
        envTemplate:
          template: "{{.TAG_ID}}"
      artifacts:
        - image: acc-ui
          context: .
          docker:
            dockerfile: Dockerfile

  - name: custom
    build:
      local:
        useDockerCLI: false
        useBuildkit: false
        tryImportMissing: true
        push: true
      tagPolicy:
        envTemplate:
          template: "{{.TAG_ID}}"
      artifacts: []
    deploy:
      kubeContext: at
      kustomize:
        paths:
          - kustomize/env/stub/custom

  - name: sysint
    build:
      local:
        useDockerCLI: false
        useBuildkit: false
        tryImportMissing: true
        push: true
      tagPolicy:
        envTemplate:
          template: "{{.TAG_ID}}"
      artifacts: []
    deploy:
      kubeContext: sysint
      kustomize:
        paths:
          - kustomize/env/aws/sysint

  - name: uat
    build:
      local:
        useDockerCLI: false
        useBuildkit: false
        tryImportMissing: true
        push: true
      tagPolicy:
        envTemplate:
          template: "{{.TAG_ID}}"
      artifacts: []
    deploy:
      kubeContext: uat
      kustomize:
        paths:
          - kustomize/env/aws/uat

  - name: demo
    build:
      local:
        useDockerCLI: false
        useBuildkit: false
        tryImportMissing: true
        push: true
      tagPolicy:
        envTemplate:
          template: "{{.TAG_ID}}"
      artifacts: []
    deploy:
      kubeContext: demo
      kustomize:
        paths:
          - kustomize/env/aws/demo

  - name: perf
    build:
      local:
        useDockerCLI: false
        useBuildkit: false
        tryImportMissing: true
        push: true
      tagPolicy:
        envTemplate:
          template: "{{.TAG_ID}}"
      artifacts: []
    deploy:
      kubeContext: perf
      kustomize:
        paths:
          - kustomize/env/aws/perf

  - name: prod
    build:
      local:
        useDockerCLI: false
        useBuildkit: false
        tryImportMissing: true
        push: true
      tagPolicy:
        envTemplate:
          template: "{{.TAG_ID}}"
      artifacts: []
    deploy:
      kubeContext: prod
      kustomize:
        paths:
          - kustomize/env/aws/prod

  - name: local
    build:
      local:
        useDockerCLI: false
        useBuildkit: false
        tryImportMissing: true
        push: true
      tagPolicy:
        envTemplate:
          template: "{{.TAG_ID}}"
      artifacts: []
    deploy:
      kubeContext: local
      kustomize:
        paths:
          - kustomize/env/stub/local/dev
