apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: acc-ui
build:
  artifacts:
    - image: acc-ui
      docker:
        dockerfile: Dockerfile
    - image: acc-cypress
      context: cypress-test
      docker:
        dockerfile: Dockerfile

profiles:
  - name: local
    manifests:
      kustomize:
        buildArgs:
          # Enable KSOPS to add plugins/execute
          - "--enable-alpha-plugins=true"
          - "--enable-exec=true"
        paths:
          - kustomize/env/stub/local/dev
  - name: at
    manifests:
      kustomize:
        buildArgs:
          # Enable KSOPS to add plugins/execute
          - "--enable-alpha-plugins=true"
          - "--enable-exec=true"
        paths:
          - kustomize/env/stub/local/at
