apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  deployedWith: kustomize
  environment: local

bases:
  - ../../../env-base

resources:
  - ../../../../config-mgmt/env/local
  - ../../../../secrets-mgmt/env/local

components:
  - ../../../../components/acc-cypress

patchesStrategicMerge:
  - acc-ui-route.yml
