apiVersion: apps/v1
kind: Deployment
metadata:
  name: acc-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acc-ui
  template:
    metadata:
      labels:
        app: acc-ui
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: acc-ui
          image: acc-ui
          resources:
            requests:
              memory: 384Mi
              cpu: 100m
            limits:
              memory: 768Mi
              cpu: 200m
          ports:
            - name: acc-port
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: acc-ui-configmap
            - secretRef:
                name: acc-ui-secrets
          # N.B. Checking external services (like Salesforce) with k8s is usually a BAD IDEA
          # We've done it because it's a necessary evil :(
          livenessProbe:
            httpGet:
              path: /api/health/details
              port: acc-port
            failureThreshold: 3
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /api/health/details
              port: acc-port
            failureThreshold: 30
            periodSeconds: 10
