apiVersion: apps/v1
kind: Deployment
metadata:
  name: acc-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acc-ui
  template:
    metadata:
      labels:
        app: acc-ui
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: acc-ui
          image: acc-ui
          resources:
            limits:
              memory: 1024Mi
              cpu: 1000m
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: acc-ui-configmap
            - secretRef:
                name: acc-ui-secrets
