apiVersion: apps/v1
kind: Deployment
metadata:
  name: acc-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acc-ui
  template:
    metadata:
      labels:
        app: acc-ui
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: acc-ui
          image: acc-ui
          resources:
            requests:
              memory: 384Mi
              cpu: 100m
            limits:
              memory: 768Mi
              cpu: 200m
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: acc-ui-configmap
            - secretRef:
                name: acc-ui-secrets
          readinessProbe:
            httpGet:
              path: /api/health/version
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          startupProbe:
            httpGet:
              path: /api/health/version
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
