execution:
- concurrency: 5
  ramp-up: 15s
  hold-for: 15s
  scenario: acc-performance-test

scenarios:
  acc-performance-test:
    requests:
    - url: http://blazedemo.com
      method: GET
      label: homepage

reporting:
- module: console
- module: passfail
  criteria:
  - avg-rt of IndexPage>150ms for 10s, stop as failed
  - fail of CheckoutPage>50% for 10s, stop as failed
- module: final-stats
  summary: true
  percentiles: true
  failed-labels: false
  test-duration: true
  dump-csv: results/final-stats/final-stats.csv
- module: junit-xml
  data-source: pass-fail
  filename: results/junit-xml/junit-result.xml
