export const specialCharFile = "specialchar@)(*&^%$£!#}{.doc";
export const singleCharFile = "T.doc";
export const longFile = "Specialcharhellothisissuperlongsowonderingifthisbailsoutinsalesforcebecausewowth1.docx";
export const testFile = "testfile.doc";
export const testFileABCad = "testfileABCadFc.doc";
export const testFileEUIFinance = "testfileEUIfc.doc";
export const testfileEUIProjectManager = "testfileEUIpm.doc";
export const noFileName = ".txt";
export const emptyFileName = " .txt";
