kind: ConfigMap
apiVersion: v1
metadata:
  name: extui-configmap
data:
  USE_SSO: "false"
  PORT: "3000"
  NODE_ENV: development
  LOG_LEVEL: VERBOSE
  ACC_ENVIRONMENT: local
  SERVER_URL: http://localhost:3000
