module.exports = {
  verbose: true,
  coverageDirectory: "dashboard/unit_testing",
  testURL: "http://localhost",
  snapshotSerializers: ["enzyme-to-json/serializer"],
  setupFilesAfterEnv: ["<rootDir>/config/jest-setup.js"],
  coveragePathIgnorePatterns: ["/node_modules/"],
  collectCoverageFrom: [
    "src/server/features/**/*.{ts,tsx}",
    "src/framework/util/*.{ts,tsx,json}",
    "src/ui/containers/**/*.{ts,tsx,json}",
    "src/ui/components/**/*.{ts,tsx,json}",
    "src/ui/hooks/**/*.{ts,tsx,json}",
    "src/ui/helpers/**/*.{ts,tsx,json}",
    "src/ui/styles/**/*.{ts,tsx,json}",
    "src/ui/redux/**/*.{ts,tsx}",
    "src/ui/validators/**/*.{ts,tsx}",
  ],
  coverageReporters: ["text", "html", "lcov"],
  transformIgnorePatterns: ["<rootDir>/node_modules/"],
  transform: {
    "^.+\\.tsx?$": "ts-jest",
  },
  testRegex: "(/tests/.*(tests|spec))\\.tsx?$",
  moduleFileExtensions: ["ts", "tsx", "js"],
  testResultsProcessor: "jest-bamboo-reporter",
  watchPlugins: ["jest-watch-typeahead/filename", "jest-watch-typeahead/testname"],
  moduleNameMapper: {
    "@server/(.*)": "<rootDir>/src/server/$1",
    "@shared/(.*)": "<rootDir>/src/shared/$1",
    "@framework/(.*)": "<rootDir>/src/framework/$1",
    "@ui/(.*)": "<rootDir>/src/ui/$1",
    "@util/(.*)": "<rootDir>/src/util/$1",
    "@content/(.*)": "<rootDir>/src/content/$1",
  },
};
