const path = require("path");

module.exports = {
  src: "./src/",
  schema: path.join("src", "gql", "schema", "fullSchema.gql"),
  language: "typescript",
  customScalars: {
    String: "string",
    EncryptedString: "string",
    Boolean: "boolean",
    Int: "number",
    Float: "number",
    Date: "string",
    DateTime: "string",
    Double: "number",
    Time: "string",
    Base64: "string",
    Id: "string",
    Currency: "number",
    TextArea: "string",
    Percent: "number",
    Phone: "string",
    URL: "string",
    Email: "string",
    AnyType: "string",
    Address: "string",
    Location: "string",
    Picklist: "string",
    MultiPicklist: "string",
    ComboBox: "string",
    Reference: "string",
    PolymorphicReference: "string",
  },
};
