type Query {
  clientConfig: ClientConfigObject!
}

type ClientConfigObject {
  features: ClientConfigFeaturesObject!
  options: ClientConfigAppOptionsObject!
  ifsRoot: String!
  ssoEnabled: Boolean!
  logLevel: LogLevel!
}

type ClientConfigFeaturesObject {
  changePeriodLengthWorkflow: Boolean!
  contentHint: Boolean!
  customContent: Boolean!
  displayOtherContacts: Boolean!
  searchDocsMinThreshold: Int!
  futureTimeExtensionInYears: Int!
}

type ClientConfigAppOptionsObject {
  maxFileSize: Int!
  maxUploadFileCount: Int!
  permittedFileTypes: [String!]!
  permittedTypes: ClientConfigAppOptionsPermittedFileTypesObject!
  bankCheckValidationRetries: Int!
  bankCheckAddressScorePass: Int!
  bankCheckCompanyNameScorePass: Int!
  standardOverheadRate: Int!
  numberOfProjectsToSearch: Int!
  maxClaimLineItems: Int!
  nonJsMaxClaimLineItems: Int!
}

type ClientConfigAppOptionsPermittedFileTypesObject {
  pdfTypes: [String!]!
  textTypes: [String!]!
  presentationTypes: [String!]!
  spreadsheetTypes: [String!]!
  imageTypes: [String!]!
}

"""The level of the logging"""
enum LogLevel {
  VERBOSE
  DEBUG
  INFO
  WARN
  ERROR
}