kind: ConfigMap
apiVersion: v1
metadata:
  name: acc-ui-configmap
data:
  ACC_ENVIRONMENT: custom
  SERVER_URL: https://www-openshiftEnvKey.openshiftEnvUrl
  USE_SSO: "false"
  NEW_RELIC_ENABLED: "false"
  FEATURE_DETAILED_ERROR_SUMMARY_COMPONENT: "true"
