apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  deployedWith: kustomize
  environment: custom

bases:
  - ../../env-base

resources:
  - ../../../config-mgmt/env/aws/custom

patchesStrategicMerge:
  - acc-ui-route.yml
