apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  deployedWith: kustomize
  environment: custom

resources:
  - ../../env-base
  - ../../../config-mgmt/env/aws/custom
  - acc-ui-route.yml
