kind: ConfigMap
apiVersion: v1
metadata:
  name: acc-ui-configmap
data:
  ACC_ENVIRONMENT: dev
  SERVER_URL: https://www-acc-dev.apps.ocp4.innovateuk.ukri.org/
  USE_SSO: "false"
  NEW_RELIC_ENABLED: "false"
