@mode:serial
Feature: Playwright Salesforce POC
    Scenario: Running a test
        #        Given the salesforce user is logged in as "ctl@capconfig.com"
        Given the salesforce user is logged in as "steven.killen@iuk.ukri.org.capconfig"
        Given there is a Competition created using the UI
        And there is a Project created using the UI
        And Contacts and Participants are added by the UI
        And Stattdate added and Project status changed to Live using the UI
        And AwardRate and CapLimit updated using UI then Claim Shell batch job ran using Apex
        And Profiles have been updated using Apex
            | fields               | value                                                                                                                                                                                       |
            | AwardRate            | 100                                                                                                                                                                                         |
            | CapLimit             | 70                                                                                                                                                                                          |
            | CompetitionType      | CR&D                                                                                                                                                                                        |
            | OrganisationType     | Industrial                                                                                                                                                                                  |
            | CostCategoriesData   | 'Subcontracting','Labour','Materials','Travel and subsistence'                                                                                                                              |
            | CostCategoryArray    | 'Labour','Subcontracting','Labour','Labour','Materials','Materials','Materials','Materials','Materials','Materials','Materials','Materials','Materials','Materials','Materials','Materials' |
            | PeriodNumberArray    | '1','1','8','11','1','2','3','4','5','6','7','8','9','10','11','12'                                                                                                                         |
            | ValueArray           | '101000','110000','100600','105000','103995','13500','100100','100200','150000','150000','510000','150000','150000','150000','510000','150000'                                              |
            | IARStatusCounter     | '5','6','7'                                                                                                                                                                                 |
            | ReviewTeamSetCounter | '1','2'                                                                                                                                                                                     |
        And claims have been added and Approved using the UI
            | Acc_ProjectPeriodNumber__c | Acc_ProjectPeriodStartDate__c | Acc_ProjectPeriodEndDate__c | Acc_TotalParticipantCosts__c | Acc_Total_Participant_Grant__c | Acc_CostsClaimedToDate__c | Acc_Grant_Paid_To_Date__c | Acc_TotalCostsSubmitted__c | Acc_Prepayment__c | Acc_DeferredGrantStaticDefGrant__c | Acc_CapLimitPercentage__c | Acc_StaticCapLimitDeferredGrant__c | Acc_StaticAwardRate__c | Acc_NewDefGrantPrepaymentCarriedForward__c | Acc_DeferredGrantToBePaid__c | Acc_OverrideGrantToBePaid__c | Acc_ParticipantCapLimit__c | Acc_NewCapLimitDeferredGrant__c | Acc_TotalCostsApproved__c | Acc_PeriodCostsApprovedForPayment__c | Acc_Approved__c | Acc_StaticDeferredGrant__c | Acc_PeriodApprovedDeferredGrant__c | Acc_ClaimStatus__c      | Acc_ApprovalStatus__c | Acc_PeriodCoststobePaid__c | Acc_DeferredApprovalStatus__c | Acc_FinalClaim__c |
            | 1.0                        | 2024-06-01                    | 2024-06-30                  | 2654395.0                    | 2123516.0                      |                           | 109999.0                  | 314995.0                   | -109999.0         |                                    | 90.0                      | 0.0                                | 80.0                   | 0.0                                        | 0.0                          |                              | 1911164.4                  | 0.0                             | 314995.0                  | 141997.0                             | true            | -109999.0                  | -109999.0                          | Payment being processed | Approved              | 141997.0                   | Approved                      | false             |
            | 2.0                        | 2024-07-01                    | 2024-07-31                  | 2654395.0                    | 2123516.0                      | 314995.0                  | 251996.0                  | 13500.0                    |                   | 0.0                                | 90.0                      | 0.0                                | 80.0                   | 0.0                                        | 0.0                          |                              | 1911164.4                  | 0.0                             | 13500.0                   | 10800.0                              | true            | 0.0                        | 0.0                                | Payment being processed | Approved              | 10800.0                    | Approved                      | false             |
            | 3.0                        | 2024-08-01                    | 2024-08-31                  | 2654395.0                    | 2123516.0                      | 328495.0                  | 262796.0                  | 100100.0                   |                   | 0.0                                | 90.0                      | 0.0                                | 80.0                   | 0.0                                        | 0.0                          |                              | 1911164.4                  | 0.0                             | 100100.0                  | 80080.0                              | true            | 0.0                        | 0.0                                | Payment being processed | Approved              | 80080.0                    | Approved                      | false             |
            | 4.0                        | 2024-09-01                    | 2024-09-30                  | 2654395.0                    | 2123516.0                      | 428595.0                  | 342876.0                  | 100200.0                   |                   | 0.0                                | 90.0                      | 0.0                                | 80.0                   | 0.0                                        | 0.0                          |                              | 1911164.4                  | 0.0                             | 100200.0                  | 80160.0                              | true            | 0.0                        | 0.0                                | Payment being processed | Approved              | 80160.0                    | Approved                      | false             |
            | 5.0                        | 2024-10-01                    | 2024-10-31                  | 2654395.0                    | 2123516.0                      | 528795.0                  | 423036.0                  | 150000.0                   |                   | 0.0                                | 90.0                      | 0.0                                | 80.0                   | 0.0                                        | 0.0                          |                              | 1911164.4                  | 0.0                             | 150000.0                  | 120000.0                             | true            | 0.0                        | 0.0                                | Payment being processed | Approved              | 120000.0                   | Approved                      | false             |
            | 6.0                        | 2024-11-01                    | 2024-11-30                  | 2654395.0                    | 2123516.0                      | 678795.0                  | 543036.0                  | 150000.0                   |                   | 0.0                                | 90.0                      | 0.0                                | 80.0                   | 0.0                                        | 0.0                          |                              | 1911164.4                  | 0.0                             | 150000.0                  | 120000.0                             | true            | 0.0                        | 0.0                                | Payment being processed | Approved              | 120000.0                   | Approved                      | false             |
            | 7.0                        | 2024-12-01                    | 2024-12-31                  | 2654395.0                    | 2123516.0                      | 828795.0                  | 663036.0                  | 510000.0                   |                   | 0.0                                | 90.0                      | 0.0                                | 80.0                   | 0.0                                        | 0.0                          |                              | 1911164.4                  | 0.0                             | 510000.0                  | 408000.0                             | true            | 0.0                        | 0.0                                | Payment being processed | Approved              | 408000.0                   | Approved                      | false             |
            | 8.0                        | 2025-01-01                    | 2025-01-31                  |                              | 2123516.0                      |                           | 0.0                       |                            |                   | 0.0                                |                           |                                    |                        |                                            | 0.0                          |                              |                            |                                 |                           | 0.0                                  | false           |                            |                                    | New                     | Pre-Approval          |                            |                               | false             |
            | 9.0                        | 2025-02-01                    | 2025-02-28                  |                              | 2123516.0                      |                           | 0.0                       |                            |                   | 0.0                                |                           |                                    |                        |                                            | 0.0                          |                              |                            |                                 |                           | 0.0                                  | false           |                            |                                    | New                     | Pre-Approval          |                            |                               | false             |
            | 10.0                       | 2025-03-01                    | 2025-03-31                  |                              | 2123516.0                      |                           | 0.0                       |                            |                   | 0.0                                |                           |                                    |                        |                                            | 0.0                          |                              |                            |                                 |                           | 0.0                                  | false           |                            |                                    | New                     | Pre-Approval          |                            |                               | false             |
            | 11.0                       | 2025-04-01                    | 2025-04-30                  |                              | 2123516.0                      |                           | 0.0                       |                            |                   | 0.0                                |                           |                                    |                        |                                            | 0.0                          |                              |                            |                                 |                           | 0.0                                  | false           |                            |                                    | New                     | Pre-Approval          |                            |                               | false             |
            | 12.0                       | 2025-05-01                    | 2025-05-31                  |                              | 2123516.0                      |                           | 0.0                       |                            |                   | 0.0                                |                           |                                    |                        |                                            | 0.0                          |                              |                            |                                 |                           | 0.0                                  | false           |                            |                                    | New                     | Pre-Approval          |                            |                               | true              |
        And claims have been added and Approved by APEX
        And approval details checked using the External UI
# And the Project has been deleted

