apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  # Specify a name
  name: acc-ui-secrets-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ../../../../acc-secrets/acc-ui-secrets.perf.yml
