apiVersion: apps/v1
kind: Deployment
metadata:
  name: acc-cypress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acc-cypress
  template:
    metadata:
      labels:
        app: acc-cypress
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: acc-cypress
          image: acc-cypress
          resources:
            requests:
              memory: 768Mi
              cpu: 250m
            limits:
              memory: 1024Mi
              cpu: 1000m
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: acc-ui-configmap
          volumeMounts:
            - mountPath: /tmp
              name: acc-cypress-temp-store
              subPath: tmp
      volumes:
        - name: acc-cypress-temp-store
          emptyDir:
            medium: Memory
            sizeLimit: 64Mi
