export * from "./dashboard/Dashboard.page";
export * from "./details/ProjectDetails.page";
export * from "./financeSummary.page";
export * from "./failedBankCheckConfirmation.page";
export * from "./documents/projectDocuments.page";
export * from "./overview.page";
export * from "./partnerDetails.page";
export * from "./partnerDetailsEdit.page";
export * from "./setup";
