export * from "./dashboard/Dashboard.page";
export * from "./details/ProjectDetails.page";
export * from "./finance-summary/financeSummary.page";
export * from "./failedBankCheckConfirmation.page";
export * from "./documents/projectDocuments.page";
export * from "./projectOverview/projectOverview.page";
export * from "./partnerDetails.page";
export * from "./partnerDetailsEdit.page";
export * from "./setup";
