import * as Containers from "@ui/containers";

export type IRoutes = typeof routeConfig;
export type RouteKeys = keyof IRoutes;

export const routeConfig = {
  allClaimsDashboard: Containers.AllClaimsDashboardRoute,
  claimsDashboard: Containers.ClaimsDashboardRoute,
  claimDetails: Containers.ClaimsDetailsRoute,
  claimDetailDocuments: Containers.ClaimDetailDocumentsRoute,
  claimDocuments: Containers.ClaimDocumentsRoute,
  claimForecast: Containers.ClaimForecastRoute,
  claimLineItems: Containers.ClaimLineItemsRoute,
  claimSummary: Containers.ClaimSummaryRoute,
  error: Containers.ErrorRoute,
  financeSummary: Containers.FinanceSummaryRoute,
  home: Containers.HomeRoute,
  monitoringReportCreate: Containers.MonitoringReportCreateRoute,
  monitoringReportDashboard: Containers.MonitoringReportDashboardRoute,
  monitoringReportDelete: Containers.MonitoringReportDeleteRoute,
  monitoringReportWorkflow: Containers.MonitoringReportWorkflowRoute,
  monitoringReportPreparePeriod: Containers.MonitoringReportPreparePeriodRoute,
  partnerDetails: Containers.PartnerDetailsRoute,
  partnerDetailsEdit: Containers.PartnerDetailsEditRoute,
  prepareClaim: Containers.PrepareClaimRoute,
  prepareClaimLineItems: Containers.EditClaimLineItemsRoute,
  projectChangeRequests: Containers.ProjectChangeRequestsRoute,
  ProjectChangeRequestAddType: Containers.ProjectChangeRequestAddTypeRoute,
  pcrCreate: Containers.PCRCreateRoute,
  pcrDetails: Containers.PCRDetailsRoute,
  pcrDelete: Containers.PCRDeleteRoute,
  pcrFinancialVirementEditPartnerLevel: Containers.FinancialVirementEditPartnerLevelRoute,
  pcrFinancialVirementEditCostCategoryLevel: Containers.FinancialVirementEditRoute,
  pcrFinancialVirementDetails: Containers.FinancialVirementDetailsRoute,
  pcrPrepare: Containers.ProjectChangeRequestPrepareRoute,
  pcrPrepareItem: Containers.PCRPrepareItemRoute,
  pcrSpendProfileCostsSummary: Containers.PCRSpendProfileCostsSummaryRoute,
  pcrSpendProfileReviewCostsSummary: Containers.PCRSpendProfileReviewCostsSummaryRoute,
  pcrPrepareSpendProfileAddCost: Containers.PCRSpendProfileAddCostRoute,
  pcrPrepareSpendProfileDeleteCost: Containers.PCRSpendProfileDeleteCostRoute,
  pcrPrepareSpendProfileEditCost: Containers.PCRSpendProfileEditCostRoute,
  pcrSpendProfileOverheadDocument: Containers.PCRSpendProfileOverheadDocumentRoute,
  pcrPrepareReasoning: Containers.PCRPrepareReasoningRoute,
  pcrReview: Containers.PCRReviewRoute,
  pcrReviewItem: Containers.PCRReviewItemRoute,
  pcrReviewReasoning: Containers.PCRReviewReasoningRoute,
  pcrViewItem: Containers.PCRViewItemRoute,
  pcrViewReasoning: Containers.PCRViewReasoningRoute,
  pcrsDashboard: Containers.PCRsDashboardRoute,
  projectDashboard: Containers.ProjectDashboardRoute,
  projectDetails: Containers.ProjectDetailsRoute,
  projectDocuments: Containers.ProjectDocumentsRoute,
  projectOverview: Containers.ProjectOverviewRoute,
  projectSetup: Containers.ProjectSetupRoute,
  projectSetupSpendProfile: Containers.ProjectSetupSpendProfileRoute,
  reviewClaim: Containers.ReviewClaimRoute,
  reviewClaimLineItems: Containers.ReviewClaimLineItemsRoute,
  forecastDashboard: Containers.ForecastDashboardRoute,
  forecastDetails: Containers.ForecastDetailsRoute,
  forecastUpdate: Containers.UpdateForecastRoute,
};
